name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'jetbrains'

    - name: Grant execute permission for gradlew
      run: |
        cd apps/android
        chmod +x gradlew

    - name: Build with Gradle
      run: |
        cd apps/android
        echo ${{ secrets.CLIENT_ID }} >> local.properties
        ./gradlew :app:assembleOssDebug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: debug-apk
        path: apps/android/app/build/outputs/apk/debug/
        compression-level: 9
